### PR TITLE
Biography update

### PR DESCRIPTION
**Pull request by 2xAA**
* added the biographies as MD documents
* tidied up tab/spacing format to use 2 spaces (just for consistency) 
* made sure the quotations in the JavaScript segments were consistent - there were more single quotes than double, so I went with singles
* made sure the watch script was watching the layouts folder instead of templates (I think metalsmith-watch is actually broken right now, thinking about repairing it)
* corrected some texts (and Dave's name) in the bios
* moved all dev-dependencies into dependencies as they're all needed for a complete build
* removed the 'docs' build folder from the repo - it doesn't need to be here I think

### CODE REVIEW

**Review by ahdinosaur — APPROVED** [review]
:+1: hey nice refactor!

**Comment by 2xAA** [comment]
Thanks @ahdinosaur! If somebody else would like to code review this (or even just clone and run on their machine) I'd be more than welcoming.
Don't particularly like merging my own PRs haha.

**Comment by 2xAA** [comment]
Oooookay. So, I just took a look at how we're currently handling deployment of the site itself.
In the ```package.json``` we have a deploy script, but this isn't being used.  
The ```docs``` folder in the master branch is set as the target for the Github Pages in the repo's settings.

This means we either:
1. use the deploy script in ```package.json``` (I think we should, keeps the master branch clean for cloning), close this PR and I'll change the ```docs``` output folder to be ```build``` instead (makes most sense imo)
2. continue storing the whole site in the ```docs``` folder in the master, close this PR and I'll re-add the docs folder to the branch

@livejs/owners - need a decision on this when you can, otherwise I'll go with option one by next Monday.  
Thanks!

**Comment by Rumyra** [comment]
There was a good reason we didn't do this and used docs instead (there was a big discussion about it)...

To deploy with a script you have to like clone, or make a branch and build and deploy and then delete - it's all super messy and blergh. This is pretty much why github created the ability to just serve from the 'docs' folder in the first place.

The deploy script doesn't even work I don't think. I was trying things out and it was really horrible. That's when gh made the docs functionality and i was all like 'phew thank god' I think we should keep it like that. ☺️

**Comment by 2xAA** [comment]
Ah ha! Okay, I must have missed this.
I'll revert my changes to keep docs and re-PR. Thanks @rumyra :)

**Comment by Rumyra** [comment]
Thanks @2xAA - sorry I totally get where you're coming from btw, I did *want* this originally.

I thought a little bit about git ignoring the docs somehow so when you branch something something - but that won't work either. And yes the thing with the watch. I was building and re commiting I think, which is a bit of a ball ache. i should probably update the readme or something...

**Pull request closed without merging**
